services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qtmdashboard-frontend
    ports:
      - "4200:80"
    # Il backend deve essere avviato separatamente
    restart: always
    networks:
      - qtm-network

networks:
  qtm-network:
    driver: bridge
