server:
  port: 8086

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/QTMDashboard?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: dago
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/QTM

app:
  keycloak:
    token-url: http://localhost:8085/realms/QTM/protocol/openid-connect/token
    client-id: postman-client
    grant-type: password
  tenants:
    default-tenant-app-url: http://localhost:4201/dashboard
    mappings:
      - client-code: app-cliente-A
        client-name: app-cliente-A
        tenant-app-url: http://localhost:4201/dashboard
        enabled: true
      - client-code: app-cliente-B
        client-name: app-cliente-B
        tenant-app-url: http://localhost:4201/dashboard
        enabled: true

logging:
  level:
    root: INFO
