server:
  port: ${SERVER_PORT:8086}

spring:
  profiles:
    active: ${QTMDB_ENV:sviluppo}
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8085/realms/QTM}

  mail:
    host: smtp.gmail.com
    port: 587
    username: francesco.tripodi@gmail.com
    password: ayekcfnurmmpwrxd
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com


app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200,http://localhost:8086}
  keycloak:
    server-url: ${APP_KEYCLOAK_SERVER_URL:http://localhost:8085}
    realm: ${APP_KEYCLOAK_REALM:QTM}
    token-url: ${APP_KEYCLOAK_TOKEN_URL:http://localhost:8085/realms/QTM/protocol/openid-connect/token}
    client-id: ${APP_KEYCLOAK_CLIENT_ID:postman-client}
    client-secret: ${APP_KEYCLOAK_CLIENT_SECRET:}
    grant-type: ${APP_KEYCLOAK_GRANT_TYPE:password}
    admin-client-id: ${APP_KEYCLOAK_ADMIN_CLIENT_ID:admin-cli-helper}
    # Previous admin client secret: xEO7e15BFOtGOoDk0MWufISzYZGdTWtc  M52taRxdhMMGjU7NvkbBkHYTLFeRWWjY
    admin-client-secret: ${APP_KEYCLOAK_ADMIN_CLIENT_SECRET:M52taRxdhMMGjU7NvkbBkHYTLFeRWWjY}
    admin-grant-type: ${APP_KEYCLOAK_ADMIN_GRANT_TYPE:client_credentials}
    admin-username: ${APP_KEYCLOAK_ADMIN_USERNAME:${KEYCLOAK_ADMIN:${KC_BOOTSTRAP_ADMIN_USERNAME:}}}
    admin-password: ${APP_KEYCLOAK_ADMIN_PASSWORD:${KEYCLOAK_ADMIN_PASSWORD:${KC_BOOTSTRAP_ADMIN_PASSWORD:}}}
    admin-user-realm: ${APP_KEYCLOAK_ADMIN_USER_REALM:master}
    client-association-attribute: ${APP_KEYCLOAK_CLIENT_ASSOCIATION_ATTRIBUTE:qtm-client-id}
  tenants:
    default-tenant-app-url: ${APP_TENANTS_DEFAULT_TENANT_APP_URL:http://localhost:8087/dashboard}
    mappings:
      - client-code: app-cliente-A
        client-name: app-cliente-A
        tenant-app-url: ${APP_TENANTS_CLIENT_A_URL:http://localhost:8087/dashboard}
        enabled: true
      - client-code: app-cliente-B
        client-name: app-cliente-B
        tenant-app-url: ${APP_TENANTS_CLIENT_B_URL:http://localhost:8087/dashboard}
        enabled: true

