server:
  port: ${SERVER_PORT:8086}

spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/QTMDashboard?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:dago}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8085/realms/QTM}

app:
  keycloak:
    server-url: ${APP_KEYCLOAK_SERVER_URL:http://localhost:8085}
    realm: ${APP_KEYCLOAK_REALM:QTM}
    token-url: ${APP_KEYCLOAK_TOKEN_URL:http://localhost:8085/realms/QTM/protocol/openid-connect/token}
    client-id: ${APP_KEYCLOAK_CLIENT_ID:postman-client}
    client-secret: ${APP_KEYCLOAK_CLIENT_SECRET:}
    grant-type: ${APP_KEYCLOAK_GRANT_TYPE:password}
    admin-client-id: ${APP_KEYCLOAK_ADMIN_CLIENT_ID:admin-cli-helper}
    admin-client-secret: ${APP_KEYCLOAK_ADMIN_CLIENT_SECRET:xEO7e15BFOtGOoDk0MWufISzYZGdTWtc}
    admin-grant-type: ${APP_KEYCLOAK_ADMIN_GRANT_TYPE:client_credentials}
    client-association-attribute: ${APP_KEYCLOAK_CLIENT_ASSOCIATION_ATTRIBUTE:qtm-client-id}
  patients:
    api-base-url: ${APP_PATIENTS_API_BASE_URL:http://localhost:8088/api}
  tenants:
    default-tenant-app-url: ${APP_TENANTS_DEFAULT_TENANT_APP_URL:http://localhost:4201/dashboard}
    mappings:
      - client-code: app-cliente-A
        client-name: app-cliente-A
        tenant-app-url: ${APP_TENANTS_CLIENT_A_URL:http://localhost:4201/dashboard}
        enabled: true
      - client-code: app-cliente-B
        client-name: app-cliente-B
        tenant-app-url: ${APP_TENANTS_CLIENT_B_URL:http://localhost:4201/dashboard}
        enabled: true

logging:
  level:
    root: INFO
