server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    sub_filter_once off;
    sub_filter_types application/javascript application/json text/css;
    sub_filter '="/' '="${FRONTEND_PATH_PREFIX}/';
    sub_filter '"/static/' '"${FRONTEND_PATH_PREFIX}/static/';
    sub_filter 'url(/' 'url(${FRONTEND_PATH_PREFIX}/';

    location = ${FRONTEND_PATH_PREFIX} {
        try_files /index.html =404;
    }

    location ^~ ${FRONTEND_PATH_PREFIX}/static/ {
        rewrite ^${FRONTEND_PATH_PREFIX}/(.*)$ /$1 break;
        try_files $uri =404;
    }

    location ${FRONTEND_PATH_PREFIX}/ {
        rewrite ^${FRONTEND_PATH_PREFIX}/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}